export const ALL_PRODUCTS_FETCH = "ALL_PRODUCTS_FETCH";
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
